In [13]:
import requests
from IPython.core.display import HTML
HTML(f"""
<style>
</style>
""")

# Question 1 b)
Focus on matrices and their operations (addition, multiplication, transpose, inverse, determinant, orthogonal). Relate them to their application within the course (e.g., transformations, basis in week 11).


- What is a matrix? 
- Matrix dimensions *n* rows, *m* columns, nxm (rowsxcolumns) matrix (talve)
- Addition -> element by element (talve)
- Scalar multiplication -> element by element
- Multiplication -> A rows == B columns (tavle)
- Transpose -> Rows = colums (talve)
- Identity matrix (tavle)
- Determinant -> Square matrix $ad-bc$ (tavle)
- Inverse -> $det \neq 0$, $AA^{-1} = I$ (tavle)
- Orthogonal -> $A^{-1} = A^{\top}$ (tavle)
- Transformations (Notebook 04-transformations)
- Basis matrix, columns are vectors in basis, $Ax=b$ where $x$ is vector tells us where $x$ is in new basis

# Linear Algebra

**Overview**
This exercise introduces fundamental linear algebra operations in Numpy and how to use them to solve linear systems of equations. The goal is to get familiarized with the concepts of linear algebra and how to use them in Numpy.


<article class="message">
    <div class="message-body">
        <strong>List of individual tasks</strong>
        <ul style="list-style: none;">
            <li>
            <a href="#diff">Task 1: Elementwise difference</a>
            </li>
            <li>
            <a href="#mul_prop">Task 2: Multiplication properties</a>
            </li>
            <li>
            <a href="#elem_mul">Task 3: Elementwise multiplication - Hadamard pr…</a>
            </li>
        </ul>
    </div>
</article>

The cell below defines matrices `A`
, `B`
, `C`
, `D`
, `E`
 that are used throughout the exercise:


In [14]:
import numpy as np
import matplotlib.pyplot as plt

In [15]:
# Define matrices to be used in the tasks:
A = np.array([
    [1, 0.5, 1/3, 0.25],
    [0.5, 1/3, 0.25, 0.2],
    [1/3, 0.25, 0.2, 1/6],
    [0.25, 0.2, 1/6, 1/7]
])

B = np.array([
    [-16, 15, -14, 13],
    [-12, 11, -10, 9],
    [-8, 7, -6, 5],
    [-4, 3, -2, 1]
])

C = np.array([
    [1, 1/2, 1/3, 1/4],
    [1/2, 1/3, 1/4, 1/5],
    [1/3, 1/5, 1/7, 1/9],
    [1/4, 1/7, 1/8, 1/9],
])

D = np.array([
    [2, 4, 5/2],
    [-3/4, 2, 0.25],
    [0.25, 0.5, 2]
])

E = np.array([
    [1, -0.5],
    [3/2, 0.5],
    [0.25, 1]
])

## Matrix Operations

---
**Task 1 (easy): Elementwise difference👩‍💻**
1. Calculate $A-B$ in the code cell below.


---

In [16]:
# Write your solution here
result = A-B
print(result)

[[ 17.         -14.5         14.33333333 -12.75      ]
 [ 12.5        -10.66666667  10.25        -8.8       ]
 [  8.33333333  -6.75         6.2         -4.83333333]
 [  4.25        -2.8          2.16666667  -0.85714286]]



---
**Task 2 (easy): Multiplication properties👩‍💻📽️**
1. Calculate $AC$ and $CA$ in the code cell below. (You may use either [`np.dot`
](https://numpy.org/doc/stable/reference/generated/numpy.dot.html<elem-3>.dot)
 or the `@`
 operator).

2. Explain why the results are different.

3. Calculate $DE$ and $ED$ in the code cell below.

4. Explain what happens and why.



---

In [17]:
# Write your solution here
ac = np.dot(A,C)
ca = np.dot(C,A)
print(f'AC: \n {ac}')
print(f'CA: \n {ca}')

de = np.dot(D, E)
print(f'DE: \n {de}')

ed = np.dot(E, D)
print(f'ED: \n {ed}')


AC: 
 [[1.42361111 0.76904762 0.53720238 0.41481481]
 [0.8        0.43968254 0.31071429 0.24166667]
 [0.56666667 0.31380952 0.22301587 0.17407407]
 [0.44126984 0.24540816 0.175      0.13689153]]
CA: 
 [[1.42361111 0.8        0.56666667 0.44126984]
 [0.8        0.46361111 0.33333333 0.26190476]
 [0.50873016 0.29126984 0.20820106 0.16301587]
 [0.39087302 0.22609127 0.16256614 0.12777778]]
DE: 
 [[8.625  3.5   ]
 [2.3125 1.625 ]
 [1.5    2.125 ]]


ValueError: shapes (3,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)


---
**Task 3 (easy): Elementwise multiplication - Hadamard product👩‍💻**
1. Calculate the elementwise multiplication of $A$ and $C$ using the `*`
 operator.
2. Explain the difference between the `*`
 and `@`
 operators and identify which one is matrix multiplication.


---

In [18]:
# Write your solution here
AC = A*C
print(AC)

[[1.         0.25       0.11111111 0.0625    ]
 [0.25       0.11111111 0.0625     0.04      ]
 [0.11111111 0.05       0.02857143 0.01851852]
 [0.0625     0.02857143 0.02083333 0.01587302]]


---
